# Generated by Django 5.2.6 on 2026-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('store', '0005_medicine_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='product_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('organization', 'product_number')},
        ),
    ]
