# Generated by Django 5.2.6 on 2026-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Pharmacist'), ('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
