# Generated by Django 5.2.6 on 2026-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Organization Admin'), ('pharmacist', 'Pharmacist'), ('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
