# Generated by Django 5.2.6 on 2026-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='components',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
    ]
