# Generated by Django 5.2.6 on 2026-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_restorelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash / In-store"),
                    ("card", "Simulated Card Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
