# Generated by Django 5.2.6 on 2026-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_order_payment_method_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash / In-store"),
                    ("card", "Simulated Card Payment"),
                    ("qr", "UPI QR Code Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
