services:
  - type: web
    name: medicare-saas
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://medicare-saas.onrender.com
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
