# Generated by Django 5.2.6 on 2026-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_assistant_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='dashboard_ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
